# Generated by Django 4.2 on 2023-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_vehicle_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.TextField(max_length=50),
        ),
    ]
