# Generated by Django 4.2 on 2023-08-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_vehicle_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(max_length=50),
        ),
    ]
